# coding: utf-8

"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.4.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.create_cluster_request_content import CreateClusterRequestContent
from openapi_client import configuration


class TestCreateClusterRequestContent(unittest.TestCase):
    """CreateClusterRequestContent unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
