# coding: utf-8

"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.4.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.cluster_status_filtering_option import ClusterStatusFilteringOption
from openapi_client import configuration


class TestClusterStatusFilteringOption(unittest.TestCase):
    """ClusterStatusFilteringOption unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
