# coding: utf-8

"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.4.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.bad_request_exception_response_content import BadRequestExceptionResponseContent
from openapi_client import configuration


class TestBadRequestExceptionResponseContent(unittest.TestCase):
    """BadRequestExceptionResponseContent unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
