# coding: utf-8

"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.4.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.get_image_log_events_response_content import GetImageLogEventsResponseContent
from openapi_client import configuration


class TestGetImageLogEventsResponseContent(unittest.TestCase):
    """GetImageLogEventsResponseContent unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
