# coding: utf-8

"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.4.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.ec2_ami_info_summary import Ec2AmiInfoSummary
from openapi_client import configuration


class TestEc2AmiInfoSummary(unittest.TestCase):
    """Ec2AmiInfoSummary unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
