# coding: utf-8

"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.4.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.list_image_log_streams_response_content import ListImageLogStreamsResponseContent
from openapi_client import configuration


class TestListImageLogStreamsResponseContent(unittest.TestCase):
    """ListImageLogStreamsResponseContent unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
