# coding: utf-8

"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.4.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class DescribeClusterResponseContent(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "creationTime",
            "cloudFormationStackStatus",
            "clusterName",
            "computeFleetStatus",
            "cloudformationStackArn",
            "lastUpdatedTime",
            "region",
            "version",
            "clusterConfiguration",
            "clusterStatus",
            "tags",
        }
        
        class properties:
            
            
            class clusterName(
                schemas.StrSchema
            ):
                pass
            region = schemas.StrSchema
            version = schemas.StrSchema
        
            @staticmethod
            def cloudFormationStackStatus() -> typing.Type['CloudFormationStackStatus']:
                return CloudFormationStackStatus
        
            @staticmethod
            def clusterStatus() -> typing.Type['ClusterStatus']:
                return ClusterStatus
            cloudformationStackArn = schemas.StrSchema
            creationTime = schemas.DateTimeSchema
            lastUpdatedTime = schemas.DateTimeSchema
        
            @staticmethod
            def clusterConfiguration() -> typing.Type['ClusterConfigurationStructure']:
                return ClusterConfigurationStructure
        
            @staticmethod
            def computeFleetStatus() -> typing.Type['ComputeFleetStatus']:
                return ComputeFleetStatus
            
            
            class tags(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Tag']:
                        return Tag
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['Tag'], typing.List['Tag']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'tags':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Tag':
                    return super().__getitem__(i)
        
            @staticmethod
            def scheduler() -> typing.Type['Scheduler']:
                return Scheduler
        
            @staticmethod
            def headNode() -> typing.Type['EC2Instance']:
                return EC2Instance
            failureReason = schemas.StrSchema
            __annotations__ = {
                "clusterName": clusterName,
                "region": region,
                "version": version,
                "cloudFormationStackStatus": cloudFormationStackStatus,
                "clusterStatus": clusterStatus,
                "cloudformationStackArn": cloudformationStackArn,
                "creationTime": creationTime,
                "lastUpdatedTime": lastUpdatedTime,
                "clusterConfiguration": clusterConfiguration,
                "computeFleetStatus": computeFleetStatus,
                "tags": tags,
                "scheduler": scheduler,
                "headNode": headNode,
                "failureReason": failureReason,
            }
    
    creationTime: MetaOapg.properties.creationTime
    cloudFormationStackStatus: 'CloudFormationStackStatus'
    clusterName: MetaOapg.properties.clusterName
    computeFleetStatus: 'ComputeFleetStatus'
    cloudformationStackArn: MetaOapg.properties.cloudformationStackArn
    lastUpdatedTime: MetaOapg.properties.lastUpdatedTime
    region: MetaOapg.properties.region
    version: MetaOapg.properties.version
    clusterConfiguration: 'ClusterConfigurationStructure'
    clusterStatus: 'ClusterStatus'
    tags: MetaOapg.properties.tags
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clusterName"]) -> MetaOapg.properties.clusterName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["region"]) -> MetaOapg.properties.region: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["version"]) -> MetaOapg.properties.version: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cloudFormationStackStatus"]) -> 'CloudFormationStackStatus': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clusterStatus"]) -> 'ClusterStatus': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cloudformationStackArn"]) -> MetaOapg.properties.cloudformationStackArn: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["creationTime"]) -> MetaOapg.properties.creationTime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lastUpdatedTime"]) -> MetaOapg.properties.lastUpdatedTime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clusterConfiguration"]) -> 'ClusterConfigurationStructure': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["computeFleetStatus"]) -> 'ComputeFleetStatus': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tags"]) -> MetaOapg.properties.tags: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scheduler"]) -> 'Scheduler': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["headNode"]) -> 'EC2Instance': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["failureReason"]) -> MetaOapg.properties.failureReason: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["clusterName", "region", "version", "cloudFormationStackStatus", "clusterStatus", "cloudformationStackArn", "creationTime", "lastUpdatedTime", "clusterConfiguration", "computeFleetStatus", "tags", "scheduler", "headNode", "failureReason", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clusterName"]) -> MetaOapg.properties.clusterName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["region"]) -> MetaOapg.properties.region: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["version"]) -> MetaOapg.properties.version: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cloudFormationStackStatus"]) -> 'CloudFormationStackStatus': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clusterStatus"]) -> 'ClusterStatus': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cloudformationStackArn"]) -> MetaOapg.properties.cloudformationStackArn: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["creationTime"]) -> MetaOapg.properties.creationTime: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lastUpdatedTime"]) -> MetaOapg.properties.lastUpdatedTime: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clusterConfiguration"]) -> 'ClusterConfigurationStructure': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["computeFleetStatus"]) -> 'ComputeFleetStatus': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tags"]) -> MetaOapg.properties.tags: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scheduler"]) -> typing.Union['Scheduler', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["headNode"]) -> typing.Union['EC2Instance', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["failureReason"]) -> typing.Union[MetaOapg.properties.failureReason, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["clusterName", "region", "version", "cloudFormationStackStatus", "clusterStatus", "cloudformationStackArn", "creationTime", "lastUpdatedTime", "clusterConfiguration", "computeFleetStatus", "tags", "scheduler", "headNode", "failureReason", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        creationTime: typing.Union[MetaOapg.properties.creationTime, str, datetime, ],
        cloudFormationStackStatus: 'CloudFormationStackStatus',
        clusterName: typing.Union[MetaOapg.properties.clusterName, str, ],
        computeFleetStatus: 'ComputeFleetStatus',
        cloudformationStackArn: typing.Union[MetaOapg.properties.cloudformationStackArn, str, ],
        lastUpdatedTime: typing.Union[MetaOapg.properties.lastUpdatedTime, str, datetime, ],
        region: typing.Union[MetaOapg.properties.region, str, ],
        version: typing.Union[MetaOapg.properties.version, str, ],
        clusterConfiguration: 'ClusterConfigurationStructure',
        clusterStatus: 'ClusterStatus',
        tags: typing.Union[MetaOapg.properties.tags, list, tuple, ],
        scheduler: typing.Union['Scheduler', schemas.Unset] = schemas.unset,
        headNode: typing.Union['EC2Instance', schemas.Unset] = schemas.unset,
        failureReason: typing.Union[MetaOapg.properties.failureReason, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DescribeClusterResponseContent':
        return super().__new__(
            cls,
            *_args,
            creationTime=creationTime,
            cloudFormationStackStatus=cloudFormationStackStatus,
            clusterName=clusterName,
            computeFleetStatus=computeFleetStatus,
            cloudformationStackArn=cloudformationStackArn,
            lastUpdatedTime=lastUpdatedTime,
            region=region,
            version=version,
            clusterConfiguration=clusterConfiguration,
            clusterStatus=clusterStatus,
            tags=tags,
            scheduler=scheduler,
            headNode=headNode,
            failureReason=failureReason,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.cloud_formation_stack_status import CloudFormationStackStatus
from openapi_client.model.cluster_configuration_structure import ClusterConfigurationStructure
from openapi_client.model.cluster_status import ClusterStatus
from openapi_client.model.compute_fleet_status import ComputeFleetStatus
from openapi_client.model.ec2_instance import EC2Instance
from openapi_client.model.scheduler import Scheduler
from openapi_client.model.tag import Tag
