# coding: utf-8

"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.4.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class Ec2AmiState(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        enum_value_to_name = {
            "PENDING": "PENDING",
            "AVAILABLE": "AVAILABLE",
            "INVALID": "INVALID",
            "DEREGISTERED": "DEREGISTERED",
            "TRANSIENT": "TRANSIENT",
            "FAILED": "FAILED",
            "ERROR": "ERROR",
        }
    
    @schemas.classproperty
    def PENDING(cls):
        return cls("PENDING")
    
    @schemas.classproperty
    def AVAILABLE(cls):
        return cls("AVAILABLE")
    
    @schemas.classproperty
    def INVALID(cls):
        return cls("INVALID")
    
    @schemas.classproperty
    def DEREGISTERED(cls):
        return cls("DEREGISTERED")
    
    @schemas.classproperty
    def TRANSIENT(cls):
        return cls("TRANSIENT")
    
    @schemas.classproperty
    def FAILED(cls):
        return cls("FAILED")
    
    @schemas.classproperty
    def ERROR(cls):
        return cls("ERROR")
