# coding: utf-8

"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.4.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class InstanceState(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        enum_value_to_name = {
            "pending": "PENDING",
            "running": "RUNNING",
            "shutting-down": "SHUTTINGDOWN",
            "terminated": "TERMINATED",
            "stopping": "STOPPING",
            "stopped": "STOPPED",
        }
    
    @schemas.classproperty
    def PENDING(cls):
        return cls("pending")
    
    @schemas.classproperty
    def RUNNING(cls):
        return cls("running")
    
    @schemas.classproperty
    def SHUTTINGDOWN(cls):
        return cls("shutting-down")
    
    @schemas.classproperty
    def TERMINATED(cls):
        return cls("terminated")
    
    @schemas.classproperty
    def STOPPING(cls):
        return cls("stopping")
    
    @schemas.classproperty
    def STOPPED(cls):
        return cls("stopped")
