# coding: utf-8

"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.4.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v3_clusters_cluster_name_computefleet.get import DescribeComputeFleet
from openapi_client.paths.v3_clusters_cluster_name_computefleet.patch import UpdateComputeFleet


class ClusterComputeFleetApi(
    DescribeComputeFleet,
    UpdateComputeFleet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
