# coding: utf-8

"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.4.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v3_clusters.post import CreateCluster
from openapi_client.paths.v3_clusters_cluster_name.delete import DeleteCluster
from openapi_client.paths.v3_clusters_cluster_name.get import DescribeCluster
from openapi_client.paths.v3_clusters.get import ListClusters
from openapi_client.paths.v3_clusters_cluster_name.put import UpdateCluster


class ClusterOperationsApi(
    CreateCluster,
    DeleteCluster,
    DescribeCluster,
    ListClusters,
    UpdateCluster,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
