# coding: utf-8

"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.4.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v3_clusters_cluster_name_logstreams_log_stream_name.get import GetClusterLogEvents
from openapi_client.paths.v3_clusters_cluster_name_stackevents.get import GetClusterStackEvents
from openapi_client.paths.v3_clusters_cluster_name_logstreams.get import ListClusterLogStreams


class ClusterLogsApi(
    GetClusterLogEvents,
    GetClusterStackEvents,
    ListClusterLogStreams,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
