# coding: utf-8

"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.4.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v3_images_custom.post import BuildImage
from openapi_client.paths.v3_images_custom_image_id.delete import DeleteImage
from openapi_client.paths.v3_images_custom_image_id.get import DescribeImage
from openapi_client.paths.v3_images_custom.get import ListImages
from openapi_client.paths.v3_images_official.get import ListOfficialImages


class ImageOperationsApi(
    BuildImage,
    DeleteImage,
    DescribeImage,
    ListImages,
    ListOfficialImages,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
